### PR TITLE
Support multiple values

### PR DESCRIPTION
**Pull request by josephcsible**
This just shows them via REST. A future commit will actually let
the HTTP Proxy expose multiple values.

### CODE REVIEW

**Comment by josephcsible** [comment]
Depends on CyclopsMC/IntegratedDynamics#521.

**Comment by rubensworks** [comment]
The [vocabulary](https://github.com/CyclopsMC/IntegratedREST/blob/master-1.12/src/main/resources/vocabulary.ttl) and [context](https://github.com/CyclopsMC/IntegratedREST/blob/master-1.12/src/main/resources/context.jsonld) will also need updating to include this new `values` predicate.

If you have no idea what that is or how to get started with it, I can look into it.

**Comment by josephcsible** [comment]
I'll give it a shot.

**Comment by josephcsible** [comment]
Hmm, I can't figure out a good name for the JSON object that contains the "values" and "valueType" keys. I want to say "Value", but that's obviously taken.

**Comment by rubensworks** [comment]
Actually, the `ir:value` predicate can be reused, so no changes are needed to the vocab. But you'll have to add this line to the context: `"values": { "@id": "ir:value" },` (at line 63?)

**Pull request closed without merging**
